### ISSUE TITLE
add "playground" tab to execute script

### ISSUE THREAD

**Issue by mathieudutour** [skpm/sketch-dev-tools#11]
would be nice to have a input in the console panel similar to the chrome devtools (or any devtools really) that would run the script.

We could even potentially add an entire panel to write a script (with eslint and stuff) and just remove the existing one in Sketch (_not discuss yet with the team so take we caution_)

**Comment by turbobabr** [comment]
> would be nice to have a input in the console panel similar to the chrome devtools (or any devtools really) that would run the script.

IMHO this one is pretty useless. Such feature exists in Chrome DevTools because there an actual session that can be evaluated via JS statements in console input. In case of Sketch - there is no such thing like `active session` or something. It might be useful or currently running command only (coscript.setShouldKeepAround=true), but that's requires some UI to select a session and all, but it's easier to achieve the same result right from the plugin's code.

> We could even potentially add an entire panel to write a script (with eslint and stuff) and just remove the existing one in Sketch (not discuss yet with the team so take we caution)

This one might be really helpful! Adding a dedicated panel called, let's say, "Playground" that allows to run `ES6 JS` and quickly install some `npm` modules to test stuff is gold!

**Comment by turbobabr** [comment]
![group](https://user-images.githubusercontent.com/6356526/32370593-a68bc72a-c0c8-11e7-87cf-c96d5ec452d4.png)

**Comment by sergimiral** [comment]
Just my 2cts: If the debugger was unique per each document, each document could act as that `active session` where the script would run. Like the current `Plugins > Run Script…` action.

In that case a possible UI solution could be making the debugger docked by default like this: 
![image](https://user-images.githubusercontent.com/1785450/32405274-ad40ffaa-c162-11e7-8086-c6cf38e7bb42.png)

Although I'm not even sure if limiting the scope of the debugger to each document is an improvement in the UX of the debugger itself or if it's adding unnecessary limits. Thoughts?

**Comment by mathieudutour** [comment]
The debugger being docked or not is independent of the context the script would receive (just like the existing `Run Script...`  panel).

Regarding the dock or floating window, I talked a bit about it here: http://sketchplugins.com/d/246-testing-plugins/17
> - the logs, model and actions are not actually bound to a document, there can be multiple documents broadcasting actions, plugins working across documents, etc.
> - as a team, we are thinking about how to provide a more "structured" way to add native UI so that not everybody tries to fight for the same space and breaks Sketch. It felt wrong for me to go and add some native UI without talking to the designers (I hacked the devtools last weekend).
> - I wanted to show an example of using https://github.com/skpm/sketch-module-web-view

I really like the "playground" tab. We can use [babel-standalone](https://github.com/babel/babel/tree/master/packages/babel-standalone) to compile the script. But I'm not sure how to bundle it with the node modules 🤔 

I was also thinking about changing the "save" button of the current panel: right now it saves a new plugin every time. How about just saving the script as a command of a "Custom scripts" plugin. That way it wouldn't pollute the plugin menu (we could save both the compiled and source scripts so that we can re-open them in the playground).

**Comment by julianburr** [comment]
The playground tab sounds cool, it definitely makes sense to have something similar to the current "Run Script" panel directly in the dev tools, I also like the idea of saving commands rather then seperate plugins every time. Alternatively you could have some kind of collections (yes, I have postman open atm 😅), so you could basically logically sort your scripts and divide them into seperate plugins as you want?!

Back to the original proposal tho, I do think it would be helpful to some extend. E.g. being able to run commands on selected layers (selected in the document or the elements tab) could be helpful for quickly testing things ... you could also connect it to the console tab, where you could select logged layers and if they still exist in the document, you could do the same thing and use this "playground" input or panel to run methods on that logged element.

**Comment by mathieudutour** [comment]
Oh the collection thing is nice, wouldn't be too hard I think

Yes I was also thinking about the "Elements" tab where you can select a layer and it could be made available as `$r` in the console (same as react-dev-tools) for example
