### ISSUE TITLE
release to update name

### ISSUE THREAD

**Issue by robintindale** [skpm/sketch-dev-tools#14]
Ah just wrote an issue that the name is confusingly inconsistent between `dev-tools` and `debugger`, but I see you've already patched it in 883b736a788df6d45989c19121dd0e1cc5624bb4 and 7b82e85880256e9e552ef8caa20b966905054859. 

Can you make a release to propagate these changes, as I just got confused installing it, because it still came up as `Debugger` in lots of places

**Comment by mathieudutour** [comment]
done!
