### ISSUE TITLE
add a preference panel

### ISSUE THREAD

**Issue by mathieudutour** [skpm/sketch-dev-tools#15]
we should add a small ⚙️ icon on the topbar to open a preference panel.

Things we could put inside:
- #13 
- window always on top or not
- dark theme 🤘
- button to clear script cache (#17)
- show timestamps
- and probably a lot more

**Comment by rayelder** [comment]
I noticed you have two issues that "need design". I'd be happy to help.

**Comment by mathieudutour** [comment]
That’d be ace 👍
