### ISSUE TITLE
Elements hangs on big document

### ISSUE THREAD

**Issue by robintindale** [skpm/sketch-dev-tools#16]
On a reasonably-sized document clicking the _Elements_ tab hangs the whole of Sketch for an extended period of time. We probably need to switch to progressively loading hierarchy based on what the user expands.

It also looks like the contents aren't cached - so if you click on a different tab and return, the whole process happens again.

**Comment by mathieudutour** [comment]
yes that's sensible. Happy to accept a PR 👍

**Comment by mathieudutour** [comment]
fixed in 0.6
