### ISSUE TITLE
No Scroll on Elements Panel when QuickLook is opened

### ISSUE THREAD

**Issue by iansoper** [skpm/sketch-dev-tools#18]
When I expand elements in the elements panel, I am unable to scroll the panel to see the entire element tree.

**Comment by romansp** [comment]
I'm willing to work on this. 

Already made it scrollable (inside both Elements and QuickLook panels), but opened `QuickLook`s are overlaying on top of each other right now. Have to figure out how to toggle them correctly. 
Branch: https://github.com/skpm/sketch-dev-tools/compare/master...romansp:f/elements-scrolling

Never worked with React before, so how do I dispatch an action to the store, so it will be handled correctly? I noticed that `dispatch` function is somehow glued via `props`. I tried adding `dispatch` prop to `ElementTreeItem`, but it's still appears as `undefined`. I'm looking at `quick-look.jsx` as an example of how to do it though.

From where does `dispatch` initially come from?

**Comment by mathieudutour** [comment]
as soon as a Component is wrapped with `connect` (from `react-redux`), it should have `dispatch` available

**Comment by mathieudutour** [comment]
I was actually thinking about using a `react-split-pane` like the playground for this. What do you think?

**Comment by romansp** [comment]
Hm, I tried `connect`ing too... Will check it more thoroughly tomorrow.

Quickly looked through `react-split-pane`. Looks promising, especially when you don't want to reinvent the wheel :smile:. Noticed that v2 of it is in the works though.

**Comment by mathieudutour** [comment]
I made a quick fix by simply removing the overlay for now
