### ISSUE TITLE
v0.4.0 upgrade on Sketch 48.1 don't work

### ISSUE THREAD

**Issue by thierryc** [skpm/sketch-dev-tools#20]
V.0.3.0 dno't work v0.4.0 on Sketch 48.1

V0.3.0: 518 678 bytes (537 KB on disk)
v0.4.0: 33 937 549 bytes (62,8 MB on disk)

**Comment by mathieudutour** [comment]
any precision? it "works" for me

**Comment by thierryc** [comment]
The button doesn’t update the plugins. Nothing appends

<img width="519" alt="update" src="https://user-images.githubusercontent.com/197471/33724056-5a63979a-db3c-11e7-9ac1-a848289e9a57.png">

**Comment by mathieudutour** [comment]
oh the button here. I messed up a link, should be fine now

**Comment by thierryc** [comment]
The 0.4.0 is 100 x Bigger than 0.3.0. (Node-module is included ?)

**Comment by thierryc** [comment]
Thank you. Mathieu.

**Comment by thierryc** [comment]
The button works

**Comment by mathieudutour** [comment]
> The 0.4.0 is 100 x Bigger than 0.3.0. (Node-module is included ?)

yes there is a new tab "playground" where you can run a script that gets compiled with webpack (you can even use npm packages in your script!)

**Comment by thierryc** [comment]
Killing features.! <3
