### ISSUE TITLE
Sketch-utils 0.1.2 does not exist

### ISSUE THREAD

**Issue by simon-dt** [skpm/sketch-dev-tools#23]
Hi,
When running `npm i`, I get the error that there is no matching version found for `sketch-utils@1.0.2`

Also, when looking at this plugin on the npm repository it shows the 0.1.1 version. Perhaps the author reverted 0.1.2?

Using 0.1.1 in sketch-dev-tools does not work. It fails on some to-array.js module parsing.

My workaround is using `"sketch-utils": "git+https://github.com/skpm/sketch-utils.git"` as dependancy but it looks like the 0.1.2 version is not published on npmjs yet or anymore.

**Comment by mathieudutour** [comment]
see https://github.com/skpm/skpm/issues/118#issuecomment-362232049

**Comment by simon-dt** [comment]
Ah, sorry, I did search for similar issues but did not see that one. Anyway, the direct git dependency works as well for now. 

Thanks for replying and pointing me to that open issue.
