### ISSUE TITLE
line numbers or jump-to-code

### ISSUE THREAD

**Issue by MareoRaft** [skpm/sketch-dev-tools#28]
Hello!  Is it possible to include the line numbers of the javascript source files in the error messages?  This used to be a thing in the old https://github.com/turbobabr/sketch-devtools plugin, and it even had a jump-to-code feature.

I don't know how hard it would be to get line numbers working, but it would be a major help.  Developing my own plugins is too opaque right now (Sketch versions 50, 51).  Have a nice day!

**Comment by mathieudutour** [comment]
Ah yes totally possible now. It was blocked for a while but fixed now.

Duplicate #9
