### ISSUE TITLE
sketch runner icon

### ISSUE THREAD

**Issue by mathieudutour** [skpm/sketch-dev-tools#3]
Did you end up finishing the icon?

**Comment by sergimiral** [comment]
I didn't yet but I'll share some ideas soon

**Comment by sergimiral** [comment]
![image](https://user-images.githubusercontent.com/1785450/32220027-75946bbc-be30-11e7-92d3-6a34a61ddc5f.png)

Yesterday I did quite some tryouts for the icon but I ended up with probably the simplest one 😅
Some notes I took during the process:

- The 64x64 icon will look pretty small and packed when surrounded by the other icons in the list.
- This icon has to be really simple so it’s clearly recognisable, or in case we decide for a more complex logo we would need to prepare a reduced version to be displayed in Runner.
- The look of this debugger should feel a bit “on-brand” (yeah, right?)
- Right now the plugin has just one command, but that might change in the future.

And then some thoughts to explain why I think this icon could work for a first version:

- Although simple, the icon is composed of two elements. That would allow us to combine other concepts in the future, like representing the actions tab as `console + sandclock` or the elements tab as `code + shapes`, for example…
- It keeps an anchor to the Sketch brand just by including the logo (duh :P) 
- The console/terminal icon and colours are super recognisable as such, plus they have perfect contrast with the rest of the elements and the backgrounds.
- When the debugger opens the first active tab is the Console, so it sort of makes sense (at least by now and until/if we add direct shortcuts for the other tabs)

**Comment by mathieudutour** [comment]
😍

**Comment by sergimiral** [comment]
![icon](https://user-images.githubusercontent.com/1785450/32275366-4b2e2832-bf0b-11e7-9f8c-39d1fa4fd345.png)
https://sketch.cloud/s/EL2DY

The png above should be ready to use and the sketch file is in sketch cloud (uploaded using the latest beta) in case you want to tweak it, create more icons or do some other magic! :)

**Comment by mathieudutour** [comment]
done :tada:
