### ISSUE TITLE
console.log not working

### ISSUE THREAD

**Issue by fnky** [skpm/sketch-dev-tools#31]
Using console.log won't add entries in the console. This seems to be broken on `master` and works fine in latest release ([v0.6.0](https://github.com/skpm/sketch-dev-tools/releases/tag/v0.6.0)).

1. Checkout `master`.
2. Run `npm link` to link the `dev-tools.sketchplugin`.
3. Run `npm watch` to build and watch for changes.
4. Issue a command which uses `console.log`.
5. See that the log doesn't appear in the console.

For a working version, checkout `v0.6.0` and follow the same steps.

**Comment by fnky** [comment]
It seems like the `Log.finish` action isn't called.

I use Sketch 51 (57462).

**Comment by fnky** [comment]
After more some more digging, I ended up filtering known actions from other actions (such as logs).

I found that things like `context.actionContext` only contains a `NSSingleEntryDictionary`:

```
__NSSingleEntryDictionaryI { action: <MSRunPluginAction: 0x608000c4a0e0> }
```

This means that things like the `payload` and level aren't `available`. Could this be an incompatibility between Sketch 50 and 51?

**Comment by mathieudutour** [comment]
re console.log not working: it's actually a bug in Sketch (it is indeed because `Log.finish` is not called). It will be fixed in the next version.

re context.actionContext: it depends on the action, sometimes there is more information than others. It didn't change tho

**Comment by fnky** [comment]
> re context.actionContext: it depends on the action, sometimes there is more information than others. It didn't change tho

Hmm, that's quite strange; When I made my "fix", the only issue was that `actionContext` didn't contain `payload` and `level`—I observed by filtering out the [documented actions](https://developer.sketchapp.com/reference/action/) to only receive (logs). This didn't seem to have `payload` and `level` on the `actionContext` object.

Am I missing something?

**Comment by mathieudutour** [comment]
should be fixed in Sketch 52, along with getting sourcemaps for the errors and getting all the logs, regardless of using skpm or not

**Comment by Serzhs** [comment]
If you are new to sketch plugins like me, then if you like to see `console.log` result added in your project, then you need to open plugins console via `inspect element` by `right click` on plugins window.
<img width="174" alt="image" src="https://user-images.githubusercontent.com/5610063/208903705-7b611418-1093-4f8a-a68c-5d64d03dc406.png">
