### ISSUE TITLE
Can't open dev tools v0.7.0

### ISSUE THREAD

**Issue by ziven27** [skpm/sketch-dev-tools#34]
<img width="500" alt="qq20180815-103228 2x" src="https://user-images.githubusercontent.com/7261176/44128619-8b8883a8-a076-11e8-992f-3858804e1fca.png">

I can't open dev tools , when I open my safafi I can see this error

**Comment by mathieudutour** [comment]
and it was working before? I think it's because you are on macOS El Capitan which ships a pretty outdated version of javascript -> https://github.com/skpm/sketch-dev-tools/issues/24

**Comment by ziven27** [comment]
My macOS is  macOS Sierra 10.12.6

**Comment by tarunmangukiya** [comment]
Same error. It was working before and after update stopped working.

**Comment by mathieudutour** [comment]
also on 10.12?

**Comment by kupe517** [comment]
This is the same issue I am having. Detailed it here: https://github.com/skpm/sketch-dev-tools/issues/25

**Comment by bialikover** [comment]
Any updates on this? 

I'm Having the same issue with On Mac OS 10.12.6 and sketch 48.2
```
[Error] SyntaxError: Unexpected token '...'. Expected a property name.
	(anonymous function)
	JSEvaluateScript
	-[Mocha evalJSString:scriptPath:]
	-[Mocha evalString:atURL:]
	-[COScript executeString:baseURL:]
	?
	?
	?
	?
	?
	?
	?
	?
	?
	_os_activity_initiate_impl
	-[NSApplication(NSResponder) sendAction:to:from:]
	-[NSMenuItem _corePerformAction]
	-[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:]
	_os_activity_initiate_impl
	-[NSMenu performActionForItemAtIndex:]
	-[NSMenu _internalPerformActionForItemAtIndex:]
	-[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:]
	NSSLMMenuEventHandler
	DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)
	SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)
	SendEventToEventTarget
	SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**)
	SendMenuCommandWithContextAndModifiers
	SendMenuItemSelectedEvent
	FinishMenuSelection(SelectionData*, MenuResult*, MenuResult*)
	MenuSelectCore(MenuData*, Point, double, unsigned int, OpaqueMenuRef**, unsigned short*)
	_HandleMenuSelection2
```

**Comment by kupe517** [comment]
Should we not expect this to be fixed at this point?

**Comment by mathieudutour** [comment]
should be fixed with v0.7.1 I believe

**Comment by kupe517** [comment]
@mathieudutour There is no compiled plugin with the 0.7.1 release. Or am I missing something?

**Comment by mathieudutour** [comment]
https://github.com/skpm/sketch-dev-tools/releases/tag/v0.7.1 ?

**Comment by kupe517** [comment]
I was missing something haha, sorry! I had originally clicked the .zip without reading the (source) part. My bad.
