### ISSUE TITLE
devtools eating logs from run script window

### ISSUE THREAD

**Issue by robintindale** [skpm/sketch-dev-tools#35]
When I updated my main Sketch to 52, I noticed that logging in the `Run Script` window stopped working. The output was still going to `~/Library/Logs...Plugin Log.log`, but it wasn't showing in the window.

When I disabled the `sketch-dev-tools` plugin, the output showed up in the window. I've since re-enabled the plugin and the logging carried on working, until I open a new `dev-tools` window, and the logging stops working again. Sometimes the logged items show up in the `dev-tools` console, but more often than not, that's blank too.

Any idea what's going on? It seems like some weird file-handle reading thing maybe?

**Comment by mathieudutour** [comment]
so there is no file reading anymore (assuming you use the latest version of `sketch-dev-tools`), it's an action now. Not sure what's happening...

**Comment by robintindale** [comment]
I'm on `0.7.1`. It's quite weird - if I restart Sketch, logging doesn't work... until I open and **close** the `dev-tools` window, then logging in `Run Script` starts working

**Comment by mathieudutour** [comment]
Ah it's a bug on Sketch, I'll try to fix it for 52.1

**Comment by robintindale** [comment]
I'm not fully sure, but will mention because it's related - I think what's showing in `skpm log -f` has changed too?

**Comment by mathieudutour** [comment]
Yeah it's the same bug

**Comment by robintindale** [comment]
The `Run Script` issue seems fixed in 52.1. But the logs are still going to `Plugin Log` rather than `Plugin Output` of the previous versions, meaning `skpm log` isn't seeing them. Is the plan to switch this back, or change where `skpm log` is looking?

**Comment by mathieudutour** [comment]
Ah yes, now instead of `Plugin Output` and `Plugin Developer` (that nobody knew about but what really useful), every thing goes to `Plugin Log`. Seems like I forgot to update skpm. Will do so now!
