### ISSUE TITLE
Unreadable font colors in 0.7.8

### ISSUE THREAD

**Issue by rutgervalk** [skpm/sketch-dev-tools#37]
I finally got the DevTools window to show but it would seem that there is an issue with some of the ui and font colors, I can't read any output unless it's highlighted through selecting.

The issue occurs whether I build from source or download the plugin from the latest release, even without other extensions installed.

Screenshots for reference.
![screen shot 2018-10-25 at 13 18 08](https://user-images.githubusercontent.com/35924142/47496989-dd84f500-d858-11e8-87ab-83dd6e512089.png)
![screen shot 2018-10-25 at 13 20 02](https://user-images.githubusercontent.com/35924142/47496990-dd84f500-d858-11e8-892d-9ba495691909.png)

**Comment by mathieudutour** [comment]
Ah my bad, messed the text color when adding the dark theme. It should be fixed in 0.7.9 (uploading now)
