### ISSUE TITLE
Having the Dev Tools plugin installed slows down layer selection dramatically

### ISSUE THREAD

**Issue by romannurik** [skpm/sketch-dev-tools#39]
When the dev tools plugin is installed (not just shown/visible), clicking around and selecting layers is painfully slow. My sense is the plugin is doing a lot of work in layer selection actions or something similar :-/

**Comment by mathieudutour** [comment]
Hum that’s weird, it’s only listening to actions when it’s shown. Maybe there is a bug there. Does it happen even when you start Sketch and don’t open the plugin?

**Comment by romannurik** [comment]
Yeah I don't think it matters if the plug-in is open... I remember having a similar issue when I had a "*" action handler in my own test plugin.

**Comment by mathieudutour** [comment]
So the dev tools change the setting to listen to the "*" action when it is shown and changed it back when it's closed.

I can imagine that either two things happened:
- you enabled the setting yourself (likely)
- Sketch crashed and the plugin didn't have time to shut down so the setting is still on (likely as well^^)

I'm guessing opening and closing the plugin should bring it back to order but maybe I could add a setting in the plugin to disable this all together (after all it's pretty rare that I need to check the actions so it could be a pretty good perf improvement anyway).

**Comment by romannurik** [comment]
Thanks for the tip! I messed around with the app-level setting per the [docs](https://developer.sketchapp.com/guides/preferences/):

    defaults write ~/Library/Preferences/com.bohemiancoding.sketch3.plist actionWildcardsAllowed -bool NO

(I switched to NO then back to YES) and it seemed to fix the problem. 🤷‍♂️
