### ISSUE TITLE
Reproducible crash when running default Playground

### ISSUE THREAD

**Issue by hamishmcneill** [skpm/sketch-dev-tools#40]
A crash occurs when attempting to run the default Playground set-up with the current releases of Sketch (53.2) and Sketch Dev Tools (0.8.0).

The Playground editor contains the following by default:

```
console.log(context)
```

**Steps to Reproduce**

1. Launch Sketch and create a new document
2. Open the Sketch Dev Tools
3. Select the *Playground* tab
4. Select the Run button

**Expected Result**

TBC (an informative error)

**Actual Result**

Sketch will crash.

**Notes**

Crash is reproducible on macOS 10.14.3 so far.

**Comment by parkerhendo** [comment]
Having this exact issue as well. Any progress or idea on how to fix?
