### ISSUE TITLE
Option log output similar to skpm log -f

### ISSUE THREAD

**Issue by KevinGutowski** [skpm/sketch-dev-tools#43]
Perhaps I misunderstand what DevTools is actually logging but when log something like ```console.log(["test","hi”])```

I get:

```
__NSFrozenDictionaryM
    >value: __NSSingleObjectArrayI
        0: >__NSFrozenDictionaryM
    >value: __NSArrayI
        0: >__NSFrozenDictionaryM
    value: test
    type: String
    primitive: String
    1: >__NSFrozenDictionaryM
         value: hi
         type: String
         primitive: String
         type: Array
primitive: Array
type: Array
primitive: Array
```

Which is often pretty helpful. (For example, I had an array of `NSCFNumbers` aka bridged `CFNumbers` and was confused why the `.includes` function wasn’t behaving as expected. I learned I needed to cast them with `Number()`). However, it would be nice to switch to a prettier output similar to what `skpm log` does.

Hopefully my feedback makes sense 🙃

**Comment by mathieudutour** [comment]
I think Sketch 54 +  DevTools 0.9 should be much better.

Can you confirm?

**Comment by KevinGutowski** [comment]
Hmmm logging that simple array looks great

```
console.log(["test","hi”])
```
<img width="705" alt="Screen Shot 2019-04-09 at 7 20 27 PM" src="https://user-images.githubusercontent.com/4199296/55846991-8cae4380-5afc-11e9-8d7b-62017d66b53e.png">

---

On the other hand, logging the wrapped `document` isn't quite helpful.

```
let sketch = require('sketch')
let document = sketch.getSelectedDocument()
console.log(document)
```
<img width="705" alt="Screen Shot 2019-04-09 at 7 21 13 PM" src="https://user-images.githubusercontent.com/4199296/55847077-da2ab080-5afc-11e9-88d1-bf9a55a84b2f.png">

---

But logging the native `document` is really helpful.

```
let sketch = require('sketch')
let document = sketch.getSelectedDocument()
console.log(document.sketchObject)
```
<img width="705" alt="Screen Shot 2019-04-09 at 7 24 59 PM" src="https://user-images.githubusercontent.com/4199296/55847171-2ece2b80-5afd-11e9-8c76-f3e381695526.png">

---

It would be nice to have best of both worlds :D

**Comment by mathieudutour** [comment]
hum interesting, `Object.keys(document)` only return `["type"]`. Did that changed?
Anyhow I can fix it

**Comment by mathieudutour** [comment]
But that's not something I can fix here (it's a bug in `console`) so I'll close this.
