### ISSUE TITLE
Sketch Devtools disappears as soon as you open a different window.

### ISSUE THREAD

**Issue by WillemvdPijl** [skpm/sketch-dev-tools#45]
Having multiple screens is nice, you are able to look at you error message on one screen, while having your code open on the other. This is not possible though with Sketch Dev tools. As soon as you open Visual Studio code or a different window, even though they don't overlap, Sketch Dev tools will close. 
It's a minor annoyance that keeps popping up.

**Comment by explorador** [comment]
+1

**Comment by mathieudutour** [comment]
I just added a new option `hidesOnDeactivate` in sketch-module-web-view to do just that.

So it should just be about update the dependency and turning off the option (`true` by default). Someone wants to send a PR?

**Comment by afifkhaidir** [comment]
Hi, I tried to solve this issue with this PR #51
