### ISSUE TITLE
v0.9.6 released version can't be opened.

### ISSUE THREAD

**Issue by random-yang** [skpm/sketch-dev-tools#50]

**Comment by funfungo** [comment]
same problem after i updated my sketch version, my sketch version is  57.1

**Comment by michelepatrassi** [comment]
same here, sketch version 55.2. For now, I downgraded to https://github.com/skpm/sketch-dev-tools/releases/tag/v0.9.5

**Comment by bialikover** [comment]
0.9.5 Works with sketch beta (Version 57 (83077)) too

**Comment by corysimmons** [comment]
Doesn't work for 53
