### ISSUE TITLE
can't open this tool

### ISSUE THREAD

**Issue by MerlinLmq** [skpm/sketch-dev-tools#53]
![image](https://user-images.githubusercontent.com/38726056/76813986-86f4ce00-6834-11ea-8efe-4500f41dd9f3.png)
![image](https://user-images.githubusercontent.com/38726056/76813996-91af6300-6834-11ea-92db-abe0160e2789.png)

**Comment by mathieudutour** [comment]
The current Sketch version is 63. Please update
