### ISSUE TITLE
sketch | unsupported plugin | extension is not compatible with your computer's CPU architecture 

### ISSUE THREAD

**Issue by newbit77** [skpm/sketch-dev-tools#76]
Hi 

im not able to use the plugin. Every time i'm trying ist, sketch fires this message: 

![Bildschirmfoto 2022-09-12 um 11 44 53](https://user-images.githubusercontent.com/23338452/189626473-ac2c4d36-237d-48b7-9bc3-8916965912bb.png)

I'm using this System-Setup: 

![Bildschirmfoto 2022-09-12 um 11 55 04](https://user-images.githubusercontent.com/23338452/189626530-f9674209-100f-47e9-aca4-9ee4d6b3b264.png)
![Bildschirmfoto 2022-09-12 um 11 55 25](https://user-images.githubusercontent.com/23338452/189626534-d3a29d32-11ac-41b9-8e3a-45f30922a030.png)

Any idea how to solve the problem?

Thanks for your help!

**Comment by mathieudutour** [comment]
duplicates of https://github.com/skpm/sketch-dev-tools/issues/62
