### ISSUE TITLE
Unsupported plugin- Sketch version:Version 93 (155335) - macOS version: macOS Monterey Version 12.5.1

### ISSUE THREAD

**Issue by cheswaytheway** [skpm/sketch-dev-tools#77]
Error message: Unsupported plugin: The extension “sketch-dev-tools” is not compatible with your computer’s CPU architecture. Please contact this extension’s developer directly for assistance.

**Comment by mathieudutour** [comment]
duplicates of https://github.com/skpm/sketch-dev-tools/issues/62
