### ISSUE TITLE
find a shortcut

### ISSUE THREAD

**Issue by mathieudutour** [skpm/sketch-dev-tools#8]
`cmd` + `option` + `i` is already taken by Intersect so we can't use it 😕

**Comment by sergimiral** [comment]
![image](https://user-images.githubusercontent.com/1785450/32320679-e0a7e6d8-bfbe-11e7-9654-3b9372d02d17.png)
In Chrome DevTools the one for the Javascript Console is `cmd`+`option`+`J`
Would that work? 🤔

**Comment by sergimiral** [comment]
Btw I was checking the original Firebug's shortcut (`F12`, not great for mac users) and I found this recent post: https://hacks.mozilla.org/2017/10/saying-goodbye-to-firebug/ 👋🔥🐞

**Comment by mathieudutour** [comment]
weirdly enough, chrome supports both shortcuts (I and J). Happy to pick J yes
